"""
app/handoff_link.py

Time-limited, HMAC-signed handoff URLs.

When a dispatcher sends the handoff to the receiving hospital, the
system generates a URL containing a signed token. The token proves the
URL was generated by the CDSS (not forged) and expires after a
configurable window (default 24 hours). No database state is required
for validation — the token is self-contained.

Security model:
- HMAC-SHA256 signed, not encrypted. The incident_id is visible in the
  URL; the token prevents tampering and forgery.
- The expiry timestamp is embedded in the signed payload and checked at
  validation time.
- A shared secret (HANDOFF_SIGNING_KEY env var, or a random key generated
  at startup) is used for HMAC. In production, this must be a stable,
  non-random secret persisted across restarts.
"""

from __future__ import annotations

import hashlib
import hmac
import os
import time
from urllib.parse import urlencode

_HANDOFF_SIGNING_KEY = os.getenv(
    "HANDOFF_SIGNING_KEY",
    "dev-handoff-signing-key-do-not-use-in-production",
)
_DEFAULT_EXPIRY_HOURS = 24


def generate_handoff_token(
    incident_id: str,
    expires_in_hours: int = _DEFAULT_EXPIRY_HOURS,
) -> str:
    """
    Generate an HMAC-SHA256 signed token embedding the incident_id and
    an expiry timestamp. The token is URL-safe and suitable for use as
    a query parameter.

    Returns a string of the form: <expiry_timestamp>.<signature>
    """
    expires_at = int(time.time()) + (expires_in_hours * 3600)
    payload = f"{incident_id}:{expires_at}"
    signature = hmac.new(
        _HANDOFF_SIGNING_KEY.encode("utf-8"),
        payload.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()
    return f"{expires_at}.{signature}"


def verify_handoff_token(incident_id: str, token: str) -> bool:
    """
    Verify that a handoff token is valid for the given incident_id.
    Returns True if the token is valid and not expired.
    """
    try:
        parts = token.split(".", 1)
        if len(parts) != 2:
            return False
        expires_at_str, signature = parts
        expires_at = int(expires_at_str)
    except (ValueError, IndexError):
        return False

    if time.time() > expires_at:
        return False

    expected_payload = f"{incident_id}:{expires_at}"
    expected_signature = hmac.new(
        _HANDOFF_SIGNING_KEY.encode("utf-8"),
        expected_payload.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()

    return hmac.compare_digest(signature, expected_signature)
