"""
app/handoff.py

Phase 5 — handoff summary.

This is a deterministic document assembled entirely from
repositories.get_incident_full(). It is NOT generated by an LLM and does
not call one. Every line in the output is either a direct field from the
incident record or a fixed-format rendering of an append-only log row
that already exists. This matches the rest of this codebase's posture:
no free-text synthesis where a structured, reproducible assembly will do,
and certainly not for a document a receiving facility will rely on at a
patient handoff.

What this deliberately does NOT do, per docs/OUT_OF_SCOPE.md:
- No narrative "clinical impression" paragraph.
- No suggested diagnosis.
- No drug-interaction or dosing commentary.
It restates what was asked, what was answered, what was measured, and
what was given — nothing inferred, nothing added.

build_handoff_summary() returns a structured dict (HandoffSummary) AND a
preformatted plain-text rendering, since a receiving facility on a radio
or a printed slip needs the text form, while a future PMIS/EHR
integration will want the structured form. Both are derived from the
same assembly call, so they cannot drift from each other.

Improvement 5 — render_audit_text() produces a complete, immutable,
timestamped export of every row associated with an incident for
medico-legal/audit purposes, with a SHA256 integrity hash at the footer.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from . import repositories as repo


@dataclass
class HandoffSummary:
    incident_id: str
    status: str
    chief_complaint: str
    priority_code: Optional[str]
    recommended_unit_type: Optional[str]
    assigned_unit_id: Optional[str]
    dispatch_protocol_id: Optional[str]
    dispatch_protocol_version: Optional[str]
    field_protocol_id: Optional[str]
    field_protocol_version: Optional[str]
    routed_facility_id: Optional[str]
    routed_facility_name: Optional[str]

    dispatch_qa: List[Dict[str, Any]] = field(default_factory=list)
    field_actions: List[Dict[str, Any]] = field(default_factory=list)
    vitals_timeline: List[Dict[str, Any]] = field(default_factory=list)
    medications_given: List[Dict[str, Any]] = field(default_factory=list)
    guidance_lookups_used: List[Dict[str, Any]] = field(default_factory=list)

    latest_vitals: Optional[Dict[str, Any]] = None
    highest_news2: Optional[Dict[str, Any]] = None
    lowest_gcs: Optional[Dict[str, Any]] = None

    text_rendering: str = ""


async def build_handoff_summary(incident_id: str) -> Optional[HandoffSummary]:
    full = await repo.get_incident_full(incident_id)
    if full is None:
        return None

    incident = full["incident"]
    vitals_history = full["vitals_history"]

    latest_vitals = vitals_history[-1] if vitals_history else None
    highest_news2 = _max_by(vitals_history, "news2_score")
    lowest_gcs = _min_by(vitals_history, "gcs_total")

    summary = HandoffSummary(
        incident_id=incident["incident_id"],
        status=incident["status"],
        chief_complaint=incident["chief_complaint"],
        priority_code=incident["priority_code"],
        recommended_unit_type=incident["recommended_unit_type"],
        assigned_unit_id=incident["assigned_unit_id"],
        dispatch_protocol_id=incident["dispatch_protocol_id"],
        dispatch_protocol_version=incident["dispatch_protocol_version"],
        field_protocol_id=incident["field_protocol_id"],
        field_protocol_version=incident["field_protocol_version"],
        routed_facility_id=incident["routed_facility_id"],
        routed_facility_name=incident["routed_facility_name"],
        dispatch_qa=full["dispatch_log"],
        field_actions=full["field_log"],
        vitals_timeline=vitals_history,
        medications_given=full["medications_given"],
        guidance_lookups_used=full["guidance_lookups"],
        latest_vitals=latest_vitals,
        highest_news2=highest_news2,
        lowest_gcs=lowest_gcs,
    )
    summary.text_rendering = _render_text(summary)
    return summary


def _max_by(rows: List[Dict[str, Any]], key: str) -> Optional[Dict[str, Any]]:
    candidates = [r for r in rows if r.get(key) is not None]
    if not candidates:
        return None
    return max(candidates, key=lambda r: r[key])


def _min_by(rows: List[Dict[str, Any]], key: str) -> Optional[Dict[str, Any]]:
    candidates = [r for r in rows if r.get(key) is not None]
    if not candidates:
        return None
    return min(candidates, key=lambda r: r[key])


def _render_text(s: HandoffSummary) -> str:
    lines: List[str] = []

    lines.append("AMBULANCE HANDOFF SUMMARY")
    lines.append(f"Incident: {s.incident_id}")
    lines.append(f"Status: {s.status}")
    lines.append("")
    lines.append(f"Chief complaint: {s.chief_complaint}")
    lines.append(f"Priority code: {s.priority_code or 'not recorded'}")
    lines.append(f"Recommended unit type: {s.recommended_unit_type or 'not recorded'}")
    lines.append(f"Assigned unit: {s.assigned_unit_id or 'not recorded'}")
    lines.append(
        f"Dispatch protocol: {s.dispatch_protocol_id or 'none'} "
        f"(v{s.dispatch_protocol_version or '-'})"
    )
    lines.append(
        f"Field protocol: {s.field_protocol_id or 'none'} "
        f"(v{s.field_protocol_version or '-'})"
    )
    lines.append(
        f"Routed facility: {s.routed_facility_name or s.routed_facility_id or 'not recorded'}"
    )
    lines.append("")

    lines.append("DISPATCH INTERVIEW (locked script, verbatim)")
    if not s.dispatch_qa:
        lines.append("  (no dispatch answers recorded)")
    for row in s.dispatch_qa:
        marker = " [BACKTRACK]" if row.get("is_backtrack") else ""
        lines.append(f"  Q: {row['question_text']}{marker}")
        lines.append(f"     A: {row['answer']}")
    lines.append("")

    if s.guidance_lookups_used:
        lines.append("SUPPLEMENTARY GUIDANCE USED (Mode 2 — informational only,")
        lines.append("did not alter the dispatch outcome above)")
        for row in s.guidance_lookups_used:
            lines.append(f"  At question {row.get('question_id') or '-'}: {row['result_summary']}")
        lines.append("")

    lines.append("VITALS TIMELINE")
    if not s.vitals_timeline:
        lines.append("  (no vitals recorded)")
    for v in s.vitals_timeline:
        lines.append(f"  {v['recorded_at']} ({v['recorded_by']})")
        parts = []
        if v.get("respiratory_rate") is not None:
            parts.append(f"RR {v['respiratory_rate']}/min")
        if v.get("spo2") is not None:
            parts.append(f"SpO2 {v['spo2']}%")
        if v.get("bp_systolic") is not None and v.get("bp_diastolic") is not None:
            parts.append(f"BP {v['bp_systolic']}/{v['bp_diastolic']}")
        if v.get("heart_rate") is not None:
            parts.append(f"HR {v['heart_rate']}bpm")
        if v.get("temperature") is not None:
            parts.append(f"Temp {v['temperature']}C")
        if v.get("consciousness"):
            parts.append(f"AVPU {v['consciousness']}")
        if v.get("news2_score") is not None:
            parts.append(f"NEWS2 {v['news2_score']} ({v.get('news2_risk_level', '-')})")
        if v.get("gcs_total") is not None:
            parts.append(f"GCS {v['gcs_total']}")
        lines.append("    " + ", ".join(parts) if parts else "    (no values recorded)")
    lines.append("")

    if s.highest_news2 is not None:
        lines.append(
            f"Highest NEWS2 during transport: {s.highest_news2['news2_score']} "
            f"({s.highest_news2.get('news2_risk_level', '-')}) at {s.highest_news2['recorded_at']}"
        )
    if s.lowest_gcs is not None:
        lines.append(
            f"Lowest GCS during transport: {s.lowest_gcs['gcs_total']} "
            f"at {s.lowest_gcs['recorded_at']}"
        )
    if s.highest_news2 is not None or s.lowest_gcs is not None:
        lines.append("")

    lines.append("MEDICATIONS / ITEMS")
    if not s.medications_given:
        lines.append("  (none recorded)")
    else:
        administered = [m for m in s.medications_given if m.get("administered", True)]
        not_administered = [m for m in s.medications_given if not m.get("administered", True)]

        lines.append("  Administered:")
        if not administered:
            lines.append("    (none)")
        for m in administered:
            lines.append(
                f"    {m['given_at']} — {m['drug_name']} {m['dose']} {m['route']} "
                f"(given by {m['given_by']})"
            )

        if not_administered:
            lines.append("  Carried / considered, NOT administered:")
            for m in not_administered:
                lines.append(
                    f"    {m['given_at']} — {m['drug_name']} {m['dose']} {m['route']} "
                    f"(logged by {m['given_by']})"
                )
    lines.append("")

    lines.append("FIELD ACTIONS / NOTES")
    if not s.field_actions:
        lines.append("  (none recorded)")
    for a in s.field_actions:
        if a.get("action_type") == "pre_arrival_confirmation":
            data = a.get("data", {})
            lines.append(
                f"  [CONFIRMED] {a['timestamp']} — Pre-arrival instructions "
                f"confirmed by {data.get('confirmed_by', '?')}. "
                f"All read: {data.get('all_instructions_read', '?')}"
            )
        else:
            detail = a["data"].get("note") or a["data"].get("step_title") or ""
            lines.append(
                f"  {a['timestamp']} — [{a['action_type']}] {detail} "
                f"(recorded by {a['recorded_by']})"
            )

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Improvement 5 — Medico-legal audit export
# ─────────────────────────────────────────────────────────────────────────────

def render_audit_text(full: Dict[str, Any]) -> str:
    """
    Produces a complete, immutable, timestamped plain-text export of every
    row associated with an incident, formatted for medico-legal/audit
    records. Takes the raw get_incident_full() dict directly (not a
    HandoffSummary) so it has access to every row ID and raw timestamp.

    Synchronous, no DB calls, deterministic — two calls to the same
    incident produce identical output. The SHA256 hash at the footer
    lets a verifier confirm the export matches the stored data.
    """
    incident = full["incident"]
    lines: List[str] = []

    # Header block
    lines.append("=" * 72)
    lines.append("INCIDENT AUDIT EXPORT")
    lines.append("=" * 72)
    lines.append(f"Incident ID: {incident['incident_id']}")
    lines.append(f"Created at: {incident.get('created_at', 'not recorded')}")
    lines.append(f"Status: {incident.get('status', 'not recorded')}")
    lines.append(f"Chief complaint: {incident.get('chief_complaint', 'not recorded')}")
    lines.append(f"Dispatch protocol: {incident.get('dispatch_protocol_id', 'none')} "
                 f"v{incident.get('dispatch_protocol_version', '-')}")
    snapshot = incident.get("dispatch_protocol_snapshot") or {}
    lines.append(f"Approved by: {snapshot.get('approved_by', 'not recorded')}")
    lines.append(f"Approved date: {snapshot.get('approved_date', 'not recorded')}")
    lines.append("")

    # Dispatch transcript block
    lines.append("-" * 72)
    lines.append("DISPATCH TRANSCRIPT (Mode 1 locked script)")
    lines.append("-" * 72)
    if not full["dispatch_log"]:
        lines.append("  (no dispatch answers recorded)")
    for row in full["dispatch_log"]:
        backtrack = " [BACKTRACK]" if row.get("is_backtrack") else ""
        lines.append(
            f"  [{row.get('timestamp', '?')}] [{row.get('id', '?')}] "
            f"Q: {row.get('question_text', '?')} | A: {row.get('answer', '?')} "
            f"| protocol_v: {row.get('protocol_version', '?')}{backtrack}"
        )
    lines.append("")

    # Guidance lookups block
    lines.append("-" * 72)
    lines.append("GUIDANCE LOOKUPS (Mode 2 — informational only)")
    lines.append("-" * 72)
    if not full["guidance_lookups"]:
        lines.append("  (no guidance lookups recorded)")
    for row in full["guidance_lookups"]:
        lines.append(
            f"  [{row.get('timestamp', '?')}] [{row.get('id', '?')}] "
            f"question_id: {row.get('question_id', '?')} "
            f"| dispatcher: {row.get('dispatcher_id', '?')} "
            f"| note: {row.get('result_summary', '?')}"
        )
    lines.append("")

    # Pre-arrival instruction confirmation block
    confirmation_rows = [
        a for a in full["field_log"]
        if a.get("action_type") == "pre_arrival_confirmation"
    ]
    if confirmation_rows:
        lines.append("-" * 72)
        lines.append("PRE-ARRIVAL INSTRUCTION CONFIRMATION")
        lines.append("-" * 72)
        for row in confirmation_rows:
            data = row.get("data", {})
            lines.append(
                f"  [CONFIRMED] [{row.get('timestamp', '?')}] "
                f"Pre-arrival instructions confirmed by {data.get('confirmed_by', '?')}. "
                f"All read: {data.get('all_instructions_read', '?')}"
            )
        lines.append("")
    else:
        lines.append("-" * 72)
        lines.append("PRE-ARRIVAL INSTRUCTION CONFIRMATION")
        lines.append("-" * 72)
        lines.append("  Not recorded")
        lines.append("")

    # Vitals block
    lines.append("-" * 72)
    lines.append("VITALS READINGS")
    lines.append("-" * 72)
    if not full["vitals_history"]:
        lines.append("  (no vitals recorded)")
    for v in full["vitals_history"]:
        lines.append(
            f"  [{v.get('recorded_at', '?')}] [{v.get('id', '?')}] "
            f"recorded_by: {v.get('recorded_by', '?')}"
        )
        parts = []
        if v.get("respiratory_rate") is not None:
            parts.append(f"RR={v['respiratory_rate']}")
        if v.get("spo2") is not None:
            parts.append(f"SpO2={v['spo2']}%")
        if v.get("spo2_scale") is not None:
            parts.append(f"scale={v['spo2_scale']}")
        if v.get("supplemental_o2") is not None:
            parts.append(f"suppO2={v['supplemental_o2']}")
        if v.get("bp_systolic") is not None:
            parts.append(f"BP_sys={v['bp_systolic']}")
        if v.get("bp_diastolic") is not None:
            parts.append(f"BP_dia={v['bp_diastolic']}")
        if v.get("heart_rate") is not None:
            parts.append(f"HR={v['heart_rate']}")
        if v.get("consciousness"):
            parts.append(f"AVPU={v['consciousness']}")
        if v.get("temperature") is not None:
            parts.append(f"Temp={v['temperature']}")
        if v.get("gcs_eye") is not None:
            parts.append(f"GCS_eye={v['gcs_eye']}")
        if v.get("gcs_verbal") is not None:
            parts.append(f"GCS_verbal={v['gcs_verbal']}")
        if v.get("gcs_motor") is not None:
            parts.append(f"GCS_motor={v['gcs_motor']}")
        if v.get("news2_score") is not None:
            parts.append(f"NEWS2={v['news2_score']}({v.get('news2_risk_level', '?')})")
        if v.get("gcs_total") is not None:
            parts.append(f"GCS_total={v['gcs_total']}")
        lines.append("    " + ", ".join(parts) if parts else "    (no values)")
    lines.append("")

    # Medications block
    lines.append("-" * 72)
    lines.append("MEDICATIONS / ITEMS")
    lines.append("-" * 72)
    if not full["medications_given"]:
        lines.append("  (none recorded)")
    for m in full["medications_given"]:
        admin_status = "ADMINISTERED" if m.get("administered", True) else "NOT ADMINISTERED"
        lines.append(
            f"  [{m.get('given_at', '?')}] [{m.get('id', '?')}] "
            f"{m.get('drug_name', '?')} {m.get('dose', '?')} {m.get('route', '?')} "
            f"| status: {admin_status} | given_by: {m.get('given_by', '?')}"
        )
    lines.append("")

    # Field actions block
    lines.append("-" * 72)
    lines.append("FIELD ACTIONS / NOTES")
    lines.append("-" * 72)
    if not full["field_log"]:
        lines.append("  (none recorded)")
    for a in full["field_log"]:
        data_str = json.dumps(a.get("data", {}), ensure_ascii=False, separators=(",", ":"))
        lines.append(
            f"  [{a.get('timestamp', '?')}] [{a.get('id', '?')}] "
            f"step_id: {a.get('step_id', '?')} | action_type: {a.get('action_type', '?')} "
            f"| recorded_by: {a.get('recorded_by', '?')} | data: {data_str}"
        )
    lines.append("")

    # Footer
    lines.append("=" * 72)
    lines.append(f"EXPORT GENERATED AT: {datetime.now(timezone.utc).isoformat()}")

    # Compute SHA256 of the serialised full dict for integrity verification
    serialised = json.dumps(full, sort_keys=True, default=str, ensure_ascii=False)
    data_hash = hashlib.sha256(serialised.encode("utf-8")).hexdigest()
    lines.append(f"INCIDENT DATA HASH (SHA256): {data_hash}")
    lines.append("=" * 72)

    return "\n".join(lines)
