"""Load processed UMLS data into PostgreSQL.

This script loads the processed JSONL and CSV files generated by combine_umls.py
into the PostgreSQL database.
"""

import csv
import json
import logging
from pathlib import Path

from api.config import settings
from api.db import Base
from api.models.umls import UMLSConcept, UMLSRelation
from sqlalchemy import create_engine, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import sessionmaker
from tqdm import tqdm

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def extract_definition(definitions: list) -> str:
    """Extract the best definition from a list of definitions.
    Prefers English definitions, otherwise returns the first one.
    """
    if not definitions:
        return None

    # Look for English definition first
    for defn in definitions:
        if isinstance(defn, dict):
            source = defn.get("source", "").upper()
            # Common English sources
            if any(eng_source in source for eng_source in ["ENG", "MSH", "NCI", "SNOMED"]):
                definition_text = defn.get("definition", "")
                if definition_text and definition_text.strip():
                    return definition_text.strip()

    # Return first non-empty definition
    for defn in definitions:
        if isinstance(defn, dict):
            definition_text = defn.get("definition", "")
            if definition_text and definition_text.strip():
                return definition_text.strip()
        elif isinstance(defn, str) and defn.strip():
            return defn.strip()

    return None


def load_concepts_from_jsonl(jsonl_path: Path, batch_size: int = 1000):
    """Load concepts from concepts.jsonl into PostgreSQL.

    Args:
        jsonl_path: Path to concepts.jsonl file
        batch_size: Number of records to process before committing
    """
    if not jsonl_path.exists():
        logger.error(f"Concepts file not found: {jsonl_path}")
        return

    engine = create_engine(settings.DATABASE_URL)
    Session = sessionmaker(bind=engine)
    session = Session()

    try:
        logger.info(f"Loading concepts from {jsonl_path}")

        # Count total lines for progress bar
        total_lines = sum(1 for _ in open(jsonl_path))
        logger.info(f"Found {total_lines:,} concepts to load")

        loaded_count = 0
        skipped_count = 0
        error_count = 0

        with open(jsonl_path) as f:
            for line_num, line in enumerate(tqdm(f, total=total_lines, desc="Loading concepts"), 1):
                try:
                    concept_data = json.loads(line.strip())

                    # Extract definition
                    definitions = concept_data.get("definitions", [])
                    definition = extract_definition(definitions)

                    # Prepare metadata (store everything except core fields)
                    metadata = {
                        "semantic_type_details": concept_data.get("semantic_type_details", []),
                        "codes": concept_data.get("codes", []),
                        "sources": concept_data.get("sources", []),
                        "term_types": concept_data.get("term_types", []),
                        "languages": concept_data.get("languages", []),
                        "all_definitions": definitions,  # Store all definitions in metadata
                    }

                    # Create concept object
                    umls_concept = UMLSConcept(
                        cui=concept_data["cui"],
                        preferred_name=concept_data.get("preferred_name", "")[
                            :500
                        ],  # Truncate if too long
                        definition=definition,
                        semantic_types=concept_data.get("semantic_types", []) or [],
                        synonyms=concept_data.get("synonyms", []) or [],
                        meta_data=metadata,
                    )

                    session.add(umls_concept)
                    loaded_count += 1

                    # Commit in batches
                    if loaded_count % batch_size == 0:
                        try:
                            session.commit()
                            logger.debug(f"Committed batch: {loaded_count:,} concepts loaded")
                        except IntegrityError as e:
                            session.rollback()
                            logger.warning(f"Integrity error at line {line_num}, skipping: {e}")
                            skipped_count += 1
                            # Try to continue with next concept
                            continue

                except json.JSONDecodeError as e:
                    logger.error(f"JSON decode error at line {line_num}: {e}")
                    error_count += 1
                    continue
                except Exception as e:
                    logger.error(f"Error processing concept at line {line_num}: {e}")
                    error_count += 1
                    session.rollback()
                    continue

        # Final commit
        try:
            session.commit()
            logger.info(f"Successfully loaded {loaded_count:,} concepts")
            if skipped_count > 0:
                logger.warning(f"Skipped {skipped_count:,} concepts (duplicates or errors)")
            if error_count > 0:
                logger.warning(f"Encountered {error_count:,} errors")
        except Exception as e:
            session.rollback()
            logger.error(f"Error in final commit: {e}")
            raise

    except Exception as e:
        session.rollback()
        logger.error(f"Fatal error loading concepts: {e}")
        raise
    finally:
        session.close()


def load_relations_from_csv(csv_path: Path, batch_size: int = 5000):
    """Load relations from relations.csv into PostgreSQL.

    Args:
        csv_path: Path to relations.csv file
        batch_size: Number of records to process before committing
    """
    if not csv_path.exists():
        logger.error(f"Relations file not found: {csv_path}")
        return

    engine = create_engine(settings.DATABASE_URL)
    Session = sessionmaker(bind=engine)
    session = Session()

    try:
        logger.info(f"Loading relations from {csv_path}")

        # Count total lines for progress bar
        with open(csv_path) as f:
            total_lines = sum(1 for _ in f) - 1  # Subtract header
        logger.info(f"Found {total_lines:,} relations to load")

        loaded_count = 0
        skipped_count = 0
        error_count = 0

        with open(csv_path) as f:
            reader = csv.DictReader(f)

            for row_num, row in enumerate(
                tqdm(reader, total=total_lines, desc="Loading relations"), 1
            ):
                try:
                    # Prepare metadata
                    metadata = {"source": row.get("source", "")}

                    # Create relation object
                    umls_relation = UMLSRelation(
                        cui1=row["cui1"],
                        cui2=row["cui2"],
                        relation_type=row["relation"][:50],  # Truncate if too long
                        relation_label=row.get("relation_label", "")[:200]
                        if row.get("relation_label")
                        else None,
                        meta_data=metadata,
                    )

                    session.add(umls_relation)
                    loaded_count += 1

                    # Commit in batches
                    if loaded_count % batch_size == 0:
                        try:
                            session.commit()
                            logger.debug(f"Committed batch: {loaded_count:,} relations loaded")
                        except IntegrityError as e:
                            session.rollback()
                            logger.warning(f"Integrity error at row {row_num}, skipping: {e}")
                            skipped_count += 1
                            continue
                        except Exception as e:
                            session.rollback()
                            logger.warning(f"Error at row {row_num}, skipping: {e}")
                            skipped_count += 1
                            continue

                except Exception as e:
                    logger.error(f"Error processing relation at row {row_num}: {e}")
                    error_count += 1
                    session.rollback()
                    continue

        # Final commit
        try:
            session.commit()
            logger.info(f"Successfully loaded {loaded_count:,} relations")
            if skipped_count > 0:
                logger.warning(f"Skipped {skipped_count:,} relations (duplicates or errors)")
            if error_count > 0:
                logger.warning(f"Encountered {error_count:,} errors")
        except Exception as e:
            session.rollback()
            logger.error(f"Error in final commit: {e}")
            raise

    except Exception as e:
        session.rollback()
        logger.error(f"Fatal error loading relations: {e}")
        raise
    finally:
        session.close()


def verify_database_connection():
    """Verify database connection and create tables if needed."""
    try:
        engine = create_engine(settings.DATABASE_URL)
        # Test connection
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        logger.info("Database connection successful")

        # Create tables if they don't exist
        Base.metadata.create_all(bind=engine)
        logger.info("Database tables verified/created")
        return True
    except Exception as e:
        logger.error(f"Database connection failed: {e}")
        logger.error(f"Please check your DATABASE_URL: {settings.DATABASE_URL}")
        return False


def main():
    """Main function to load all processed data."""
    logger.info("Starting data load process")

    # Verify database connection
    if not verify_database_connection():
        logger.error("Cannot proceed without database connection")
        return

    # Set up paths
    data_dir = Path("data/umls/processed")

    # Load concepts
    concepts_file = data_dir / "concepts.jsonl"
    if concepts_file.exists():
        logger.info("=" * 60)
        load_concepts_from_jsonl(concepts_file, batch_size=1000)
    else:
        logger.warning(f"Concepts file not found: {concepts_file}")

    # Load relations
    relations_file = data_dir / "relations.csv"
    if relations_file.exists():
        logger.info("=" * 60)
        load_relations_from_csv(relations_file, batch_size=5000)
    else:
        logger.warning(f"Relations file not found: {relations_file}")

    logger.info("=" * 60)
    logger.info("Data load process completed")


if __name__ == "__main__":
    main()
